# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Medusa.js app to Azure Web App - buaziz-medusa

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' # Medusa recommends Node.js 20+, but 22.x is also fine if available

      - name: Enable Corepack (for Yarn)
        run: corepack enable

      - name: Install dependencies and build Medusa
        run: |
          yarn install --frozen-lockfile # Use --frozen-lockfile for CI environments
          yarn build # Compiles Medusa and its plugins

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: medusa-app # Name of the artifact
          path: . # This will upload the entire project directory after build
          # Consider adding an exclusion for dev dependencies if yarn install --production is not used
          # Example (if you build a specific 'dist' or 'build' folder, use that path instead of '.'):
          # path: ./build # Or wherever Medusa outputs its production-ready files
          # Make sure to include package.json, yarn.lock, and any other runtime-essential files if you filter the path

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: medusa-app # Matches the name used in the build job

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7E875330B2E64D6989EDDAD83C5E53DB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_776FDA5677414DFC969D55C411FF7FC5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_134314781C8C40F9B74B4254A5BC887D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'buaziz-medusa'
          slot-name: 'Production'
          package: . # This will deploy the downloaded artifact (the entire project directory)
