# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Medusa.js to Azure Web App - buaziz-medusa

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Enable Yarn with Corepack
        run: corepack enable

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: (Optional) Build Medusa
        run: yarn build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: medusa-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: medusa-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7E875330B2E64D6989EDDAD83C5E53DB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_776FDA5677414DFC969D55C411FF7FC5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_134314781C8C40F9B74B4254A5BC887D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'buaziz-medusa'
          slot-name: 'Production'
          package: ./ --exclude=node_modules
          
